version: "3"

networks:
  nrv.db.1:
    driver: bridge
  nrv.db.2:
    driver: bridge
  nrv.net.1:
    driver: bridge
  nrv.net.2:
    driver: bridge

services:

  php-api:
    hostname: interface-backend
    image: 'canals/php:latest'
    ports:
      - "8021:80"
    volumes:
      - ../nrv.api/public:/var/www/html
      - ../nrv.api/src:/var/www/src
    working_dir: /var/www/html
    networks:
      - nrv.db.1
      - nrv.net.1
      - nrv.net.2
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=nrvuser
      - DB_PASSWORD=nrvpass
      - DB_NAME=nrvdb

  mysql-db:
    hostname: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassuseless
      - MYSQL_USER=nrvuser
      - MYSQL_PASSWORD=nrvpass
      - MYSQL_DATABASE=nrvdb
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - "8001:3306"
    networks:
      - nrv.db.1
      - nrv.db.2

  phpmyadmin-manager:
    hostname: php-my-admin
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql-db
    ports:
      - "8011:80"
    networks:
      - nrv.db.2
    depends_on:
      - mysql-db

  nginx-client:
    hostname: nginx-client
    image: nginx
    ports:
      - "8121:80"
    volumes:
      - ../nrv.web/client/src/html:/usr/share/nginx/html
      - ../nrv.web/client/src/css:/usr/share/nginx/html/css
      - ../nrv.web/client/src/js:/usr/share/nginx/html/js
      - ../nrv.web/client/src/image:/usr/share/nginx/html/image
      - ../nrv.web/client/src/json:/usr/share/nginx/html/json
      - ../nrv.web/client/src/scss:/usr/share/nginx/html/scss
    networks:
      - nrv.net.1
    depends_on:
      - php-api

  nginx-backoffice:
    hostname: nginx-backoffice
    image: nginx
    ports:
      - "8221:80"
    volumes:
      - ../nrv.web/backoffice:/usr/share/nginx/html
    networks:
      - nrv.net.2
    depends_on:
      - php-api