version: "3"

networks:
  nrv.net:
    driver: bridge


services:

  php-api:
    hostname: interface-backend
    image: 'canals/php:latest'
    ports:
      - "18021:80"
    volumes:
      - ../nrv.api/public:/var/www/html
      - ../nrv.api/src:/var/www/src
    working_dir: /var/www/html
    networks:
      - nrv.net

    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=nrvuser
      - DB_PASSWORD=nrvpass
      - DB_NAME=nrvdb

  mysql-db:
    hostname: mysql:5.7
    image: mysql
    command: --lower_case_table_names=2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassuseless
      - MYSQL_USER=nrvuser
      - MYSQL_PASSWORD=nrvpass
      - MYSQL_DATABASE=nrvdb
    volumes:
      - ./databasesv2:/var/lib/mysql
    ports:
      - "18001:3306"
    networks:
      - nrv.net

  phpmyadmin-manager:
    hostname: php-my-admin
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "18011:80"
    networks:
      - nrv.net
    depends_on:
      - mysql-db


  adminer:
    image: adminer
    ports:
      - "18012:8080"
    networks:
      - nrv.net
    depends_on:
      - mysql-db

  nginx-client:
    hostname: nginx-client
    image: nginx
    ports:
      - "18121:80"
    volumes:
      - ../nrv.web/client/src/html:/usr/share/nginx/html
      - ../nrv.web/client/src/css:/usr/share/nginx/html/css
      - ../nrv.web/client/src/js:/usr/share/nginx/html/js
      - ../nrv.web/client/src/image:/usr/share/nginx/html/image
      - ../nrv.web/client/src/json:/usr/share/nginx/html/json
      - ../nrv.web/client/src/scss:/usr/share/nginx/html/scss
    networks:
      - nrv.net
    depends_on:
      - php-api

  nginx-backoffice:
    hostname: nginx-backoffice
    image: nginx
    ports:
      - "18221:80"
    volumes:
      - ../nrv.web/backoffice:/usr/share/nginx/html
    networks:
      - nrv.net
    depends_on:
      - php-api